### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by mcjp78**

### CODE REVIEW

**Comment by mwmahlberg** [comment]
Tyvm!

**Comment by mwmahlberg** [comment]
@mcjp78 There seems to be a problem when compiling on travis. https://travis-ci.org/mwmahlberg/spark-template-thymeleaf/builds/133758993

**Comment by mcjp78** [comment]
Ahh, its having an issue casting the capture to an object..

All I did was update the dependencies to support it. Perhaps you can fix it?

Sent from my iPhone

On May 29, 2016, at 11:32 AM, Markus Mahlberg <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcjp78<https://github.com/mcjp78> There seems to be a problem when compiling on travis. https://travis-ci.org/mwmahlberg/spark-template-thymeleaf/builds/133758993

-

**Comment by mwmahlberg** [comment]
@mcjp78 I have not touched Java for more than a year, so it is probably not the best idea ;) And I am pretty tied into other stuff at the moment. I'd appreciate if you could have a look at it. If you wish, I can hand over the repo or make you a co-admin to improve the workflow.

**Comment by mcjp78** [comment]
Ah I see, all right I will see if I can fix it

Sent from my iPhone

On May 30, 2016, at 2:57 AM, Markus Mahlberg <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcjp78<https://github.com/mcjp78> I have not touched Java for more than a year, so it is probably not the best idea ;) And I am pretty tied into other stuff at the moment. I'd appreciate if you could have a look at it. If you wish, I can hand over the repo or make you a co-admin to improve the workflow.

-

**Pull request merged**
